<?php
/**
 * @package vo
 * @class ErpGrupos
 * @vars GRPnId,GRPsNome,GRPlDescricao,GRPdAlteracao,GRPdInclusao
 * Generated by AMFPHP Advisor on Thu Feb 3 22:18:44 GMT-0200 2011
 */
class ErpGrupos {

  // CLASS VARIABLES 

  var $GRPnId;
  var $GRPsNome;
  var $GRPlDescricao;
  var $GRPdAlteracao;
  var $GRPdInclusao;

  // The corresponding ActionScript Value Object
  var $_explicitType = "vo.ErpGrupos";

  // CONSTRUCTOR 

  function ErpGrupos() 
  {
    
  } 


}
?>